#!/usr/bin/env ruby

require 'dotenv/load'
require 'rubygems'
require 'dogapi'
require 'json'

api_key=ENV['DATADOG_API_KEY']
app_key=ENV['DATADOG_APP_KEY']

dog = Dogapi::Client.new(api_key, app_key)

# Get all downtimes
print(dog.get_all_downtimes().to_json)